version: 2
updates:
  # VS Code integration
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 15
    target-branch: main
    reviewers:
    - spicelang/gh-actions-team
    assignees:
    - spicelang/gh-actions-team